title: A Hoy! Multimedia Production Consulting
description: I'm Emma, a multimedia production consultant. I help businesses and individuals create and manage their multimedia content.
show_downloads: true
google_analytics:
theme: jekyll-theme-dinky